version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
      - name: product
        identifier: raw_product
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: sales
        identifier: raw_sales
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_ship
        columns:
        - name: orders_id
          tests:
            - unique
            - not_null