version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
      - name: product
        identifier: raw_product
      - name: sales
        identifier: raw_sales
      - name: ship
        identifier: raw_ship